### PR TITLE
Update AS + remove node_modules

### PR DESCRIPTION
**Pull request by MaxGraey**
**before**
```
1a 1b 14.595301032066345 ms 
 2a 2b 11.268491983413696 ms 
 3a 3b 6.703436970710754 ms 
 4a 4b 29.521427989006042 ms 
 5a 5b 3.3352839946746826 ms 
 6a 6b 5.667168021202087 ms 
 6a 6a 2.4267460107803345 ms

Total Running Time: 73.51785600185394
```

**after**

```
1a 1b 6.036747992038727 ms 
 2a 2b 10.801351010799408 ms 
 3a 3b 4.9172850251197815 ms 
 4a 4b 27.71406799554825 ms 
 5a 5b 2.2490650415420532 ms 
 6a 6b 4.5073660016059875 ms 
 6a 6a 1.2836679816246033 ms 

Total Running Time: 57.50955104827881
```

### CODE REVIEW

**Comment by MaxGraey** [comment]
Could you re-bench this with real word test suite from `pixelmatch.js`? As I remember we haven't significant performance difference, so I wonder how about for now

**Comment by JamesLMilner** [comment]
@MaxGraey thanks for this PR :tada: Yes I will look into the overall performance for the Mapbox rendering tests. I'm also thinking about adding a more complicated 'real worrld' test to the benchmarking suites to help track the performance across larger images.

**Comment by MaxGraey** [comment]
Sounds interesting!

**Comment by JamesLMilner** [comment]
@MaxGraey here's the timings for the Mapbox GL rendering suite test:

Screenshot_20190926_221547

Here the results are fairly comparable but JS comes out slightly faster on average

**Comment by MaxGraey** [comment]
Btw I found another repo which compare AS, JS, C++ and Rust:
https://github.com/bokuweb/wasm-pixelmatch

**Comment by MaxGraey** [comment]
It uses slightly different approach. And that's results in Chrome 77
Снимок экрана 2019-09-27 в 00 29 57

**Comment by MaxGraey** [comment]
`asInline` is some routine functions with `inline` decorator. Also there used half year old AS compiler

**Pull request merged**
